version: "3"
services:
  recipe-store-mysql:
    image: "mysql/mysql-server:8.0"
    container_name: "recipe-store-mysql"
    ports:
      - "3307:3306"
      - "33070:33060"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=recipestore
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
